module.exports = async (run, ev, tp, p) => {
  await run(6, 'calendar, halloween, health, clinic, rep, achievements', async () => {
    tp(await ev(() => { const g = SH.G, t0 = g.t, out = []; [0, 26, 57, 88, 120, 400].forEach((d) => { g.t = t0 + d * 1440; out.push(SH.dateStr() + '/' + SH.World2.season(g.t)); }); g.t = t0; return out.join(' | '); }));
    tp(await ev(() => { const g = SH.G; const v = T.go('town'); const d0 = SH.day(); g.t += (31 - (SH.START_DATE.day + d0 - 1)) * 1440; g.t = Math.floor(g.t / 1440) * 1440 + 18 * 60; g.flags.trickOrTreat = 0; SH.Atlas.hub(); const a = SH.dateStr() + ' halloween=' + SH.World2.halloween() + ' mods=' + SH.Atlas.mods.map((f) => { try { return f(v, 0.1).toFixed(2); } catch (e) { return 'E'; } }).join(','); T.clk('trick-or-treating'); return a + '\n' + T.text().slice(0, 400); }));
    tp(await ev(() => { const g = SH.G; g.phase = 'run'; g.room = null; g.base = null; g.hp = { cold: 0, blist: 0, debt: 0 }; const d = SH.K.daily; for (let i = 0; i < 12 && !g.hp.cold; i++) { g.s.warmth = 10; g.s.energy = 60; d.forEach((f) => { try { f(); } catch (e) {} }); } const c1 = g.hp.cold; g.s.warmth = 80; g.room = { pid: 'x', n: 'm', k: 'loose', until: g.t + 1e6 }; d.forEach((f) => { try { f(); } catch (e) {} }); const c2 = g.hp.cold; g.room = null; return `cold after cold nights ${c1} → a warm night in a room ${c2}; line: ${SH.World2.hpLine()}`; }));
    tp(await ev(() => { const g = SH.G; g.hp = { blist: 70, cold: 50, debt: 0 }; g.s.energy = 80; g.money = 100; g.t = Math.floor(g.t / 1440) * 1440 + 11 * 60; const v = T.go('town'); SH.Atlas.hub(); const has = T.acts().find((x) => /Clinic/.test(x)); T.clk('Clinic'); T.clk('See the nurse'); return has + '\n' + T.text().slice(0, 300) + ' hp ' + JSON.stringify(g.hp); }));
    tp(await ev(() => { if (/Thank her/.test(T.text())) T.clk('Thank her'); const v = SH.Atlas.here(), g = SH.G; g.biz = { [v.id]: { kind: 'lemonade', name: 'Frog Stand', roles: {}, shifts: 11, total: 150, pid: v.id } }; SH.Atlas.hub(); T.clk('You & your group'); T.clk('How you'); return T.text().slice(0, 400); }));
    tp(await ev(() => { SH.World2.check(); const got = SH.World2.got(); SH.K.meOpen(SH.Atlas.here()); T.clk('Achievements'); return got.length + ' got: ' + got.join(',') + '\n' + T.text().slice(0, 300); }));
  });
};
