module.exports = async (run, ev, tp, p) => {
  const say = async (lines) => { const out = []; for (const l of lines) { await ev((l) => { const i = document.querySelector('#tin'); if (!i) return; i.value = l; SH.Talk.say(); }, l); await p.waitForTimeout(1700); out.push('> ' + l + '\n  ' + await ev(() => { const x = [...document.querySelectorAll('#tlog .tl.npc')].pop(); return x ? x.innerText : '(none)'; })); } return out.join('\n'); };
  await run(4, 'parents, cover, disguise, police', async () => {
    tp(await ev(() => { const g = SH.G; g.away = null; g.party = ['nia']; SH.Friends.st('nia').joinedAt = g.t; const a = SH.Actions.list().acts.filter((x) => /note/.test(x.label)).map((x) => x.label); SH.Parents.note('nia'); document.querySelector('#kask').value = "Mom, I'm okay and safe. I'm with Sam, we're together. I love you, I'm sorry, it's not your fault. I'll call soon, I promise."; document.querySelector('#kaskOk').click(); return a.join('|') + ' → ' + JSON.stringify(SH.G.pw.nia) + ' log: ' + [...document.querySelectorAll('#log .l, #log div')].slice(-1).map((x) => x.innerText).join(''); }));
    tp(await ev(() => { const g = SH.G; for (let i = 0; i < 72; i++) SH.advance(60, { interrupt: false }); return 'after 3 days pw ' + g.pw.nia.w.toFixed(0) + ' chirp ' + g.pw.nia.chirp + ' mom ' + g.pw.nia.mom + '\nhost thread: ' + (g.threads.host_nia || []).map((m) => m.text).slice(-3).join(' / ') + '\nmom: ' + (g.threads.mom || []).slice(-1).map((m) => m.text); }));
    tp(await ev(() => { const B = SH.Brain.host_nia, A = SH.NLP.analyze, c = { ctx: 'text', mem: {}, turn: 1 }; return ['she is safe, we are together and eating', "please don't call the police", 'we are coming home tomorrow', 'we are in ' + SH.Atlas.data().places[30].name].map((t) => '> ' + t + '\n  ' + B(A(t), c).say).join('\n') + '\navailable host_nia: ' + SH.Phone.available('host_nia'); }));
    tp(await ev(() => { const v = T.go('village'); SH.Atlas.hub(); const hasMe = T.acts().some((x) => /You & your group/.test(x)); T.clk('You & your group'); const me = T.acts().join(' | '); T.clk('Your story'); T.clk('Visiting my grandma'); document.querySelector('#kask').value = 'Jordan'; document.querySelector('#kaskOk').click(); return hasMe + ' ME: ' + me + '\ncover ' + JSON.stringify(SH.G.cover[v.id]); }));
    tp(await ev(() => { const v = SH.Atlas.here(), w = v.people[0], c = { turn: 1, mem: {}, used: {}, opts: { local: w, place: v } }, A = SH.NLP.analyze; return ['whose kid are you? i am visiting', 'my name is Alex'].map((t) => '> ' + t + '\n  ' + SH.Brain.local(A(t), c).say).join('\n') + ' notice ' + SH.G.awayNotice; }));
    tp(await ev(() => { SH.G.reported = true; const v = SH.Atlas.here(); const n0 = SH.G.awayNotice; SH.Identity.mirror(v); T.clk('Cut it yourself'); T.clk('Okay'); SH.addBag('x_glasses', true); T.clk('Wear glasses'); T.clk('Okay'); const mods = SH.Atlas.mods.map((f) => f(v, 0.1).toFixed(2)).join(','); return T.text().slice(0, 160) + ' | look ' + JSON.stringify(SH.G.look) + ' mods ' + mods; }));
    await p.waitForTimeout(300); tp('before police: ' + (await ev(() => T.text())).slice(0, 120)); await ev(() => { const v = T.go('town'); SH.G.heat = 0; SH.G.party = []; SH.Police.stop(v, 'business'); });
    tp(await say(['it is for charity', 'the Happy Paws puppy fund', 'my name is Jordan', 'yes officer, sorry']));
    await p.waitForTimeout(400); tp(await ev(() => 'charityCheck ' + JSON.stringify(SH.G.flags.charityCheck) + ' excuse ' + JSON.stringify(SH.G.excuse)));
    await ev(() => { SH.Talk.close(); SH.Police.stop(SH.Atlas.here(), 'business'); });
    tp(await say(['it is a school project']));
    await ev(() => SH.Talk.close());
  });
};
