/* SMALL HOURS — ambient life, all data. Pools: mundane (things that just happen), notify (phone buzzes),
   run (street life while you're gone), story (world reactions like rumor fallout). */
(function (SH) {
  SH.Engine.register([
    /* ---------------- mundane: absolutely nothing to do with the plot ---------------- */
    { id: 'm_bus_late', pool: 'mundane', when: ['loc in bus,school,store,mall', 'hour > 7', 'hour < 20'], cooldown: 30, texts: ['The city bus is eleven minutes late. A man in a suit checks his watch every forty seconds like it\'s personally betraying him.', 'Someone taped a sign to the bus shelter: "THE 4 IS A MYTH." Somebody else added: "the 4 is a state of mind."'] },
    { id: 'm_umbrella', pool: 'mundane', when: ['wet', 'outdoor', 'phase == home'], cooldown: 60, title: 'Umbrella', text: 'A woman runs for the bus and her umbrella blows inside out, then out of her hand, then down the street like it has somewhere to be. It stops at your feet.',
      choices: [{ t: 'Run it back to her', effects: ['stat.mood +5', 'time +5'], text: 'She\'s already on the bus. She waves at you through the fogged window, mouthing "KEEP IT." You now own a slightly broken umbrella.', textCls: 'good' },
        { t: 'Keep it. Finders keepers.', effects: ['item +umbrella'], text: 'It has a bent rib and smells like someone else\'s perfume. It works.' }] },
    { id: 'm_shop_early', pool: 'mundane', when: ['hour > 17', 'hour < 21', 'loc != store'], cooldown: 72, text: 'A handwritten sign goes up in the QuikMart window across the street: "CLOSED EARLY — FAMILY THING — SORRY — RAJ." Somebody\'s night is going worse than yours.' },
    { id: 'm_dog_follow', pool: 'mundane', when: ['outdoor', '!wet', 'hour > 8', 'hour < 19'], cooldown: 48, texts: ['A golden retriever with no owner in sight is following a mail carrier from house to house, carrying a stick. The mail carrier has accepted this.', 'A small furious dog is escorting a jogger out of its territory. The jogger is doing her best.'] },
    { id: 'm_pigeon', pool: 'mundane', when: ['loc in park,mall,bus,diner', '!wet'], cooldown: 60, text: 'A pigeon steals an entire french fry from a toddler, maintains eye contact with the parent, and flies away. Nobody knows what to do. You respect it a little.' },
    { id: 'm_power_flicker', pool: 'mundane', when: ['athome', 'weather in storm,rain'], cooldown: 48, text: 'The lights flicker. The microwave clock resets to 12:00 and blinks. From downstairs, Rick: "OH, COME ON."' },
    { id: 'm_ice_cream', pool: 'mundane', when: ['outdoor', 'hour > 14', 'hour < 18', 'temp > 50'], cooldown: 96, text: 'An ice cream truck is playing "Pop Goes the Weasel" in October, at half speed, like a horror movie. It does not stop for anyone.' },
    { id: 'm_lost_cat', pool: 'mundane', when: ['outdoor'], cooldown: 96, texts: ['A LOST CAT poster on a telephone pole: "MR. BISCUITS. ANSWERS TO NOTHING. BITES." Below it, someone has written "good for him."', 'A lost-dog poster, sun-faded: "BUSTER — REWARD." It\'s been there since summer. You hope Buster is okay somewhere.'] },
    { id: 'm_car_alarm', pool: 'mundane', when: ['hour > 19'], cooldown: 48, text: 'A car alarm goes off somewhere and runs through all six of its sounds. Then again. Nobody comes.' },
    { id: 'm_fire_drill', pool: 'mundane', when: ['loc == school', 'hour > 9', 'hour < 14', 'weekday'], cooldown: 120, text: 'Fire drill. Everyone stands on the soccer field in the cold for twenty minutes while Mr. Dale counts heads wrong three times. Jordan pretends to be a news reporter. Honestly: best part of the day.', effects: ['stat.mood +4'] },
    { id: 'm_sub', pool: 'mundane', when: ['loc == school', 'hour > 8', 'hour < 12', 'weekday'], cooldown: 120, text: 'There\'s a substitute in math. He puts on a documentary about sharks and falls asleep. Thirty kids silently agree to protect this peace.', effects: ['stat.stress -4'] },
    { id: 'm_directions', pool: 'mundane', when: ['outdoor', 'hour > 9', 'hour < 19'], cooldown: 72, title: 'Directions', text: 'An old man in a Korean War veteran cap asks you, very politely, how to get to the library. He\'s holding a map from 1994.',
      choices: [{ t: 'Walk him halfway', effects: ['time +10', 'stat.mood +6'], text: 'He tells you about a dog he had in 1961 named General. General sounds like he was a great dog. At the corner he shakes your hand like you\'re a grown-up.', textCls: 'good' }, { t: 'Point and keep walking', text: '"Thank you, young man— young person." He sets off, very slowly, the wrong way.' }] },
    { id: 'm_rainbow', pool: 'mundane', when: ['weather == rain', 'hour > 15', 'hour < 18', 'chance 0.4'], cooldown: 96, text: 'The rain stops and, just for a minute, there\'s a double rainbow over the water tower. You don\'t take a picture. You just look.', effects: ['stat.mood +6'] },
    { id: 'm_kid_icecream', pool: 'mundane', when: ['loc in mall,park'], cooldown: 96, text: 'A kid drops an entire ice cream cone, looks at it, looks at his dad, and decides not to cry. The dad gives him a high five. It\'s a small thing. It stays with you.' },
    { id: 'm_neighbor_mow', pool: 'mundane', when: ['athome', 'hour > 9', 'hour < 12', '!wet', 'wd >= 5'], cooldown: 96, text: 'Mr. Henderson is mowing his lawn in a bathrobe again. He mows in stripes. He is very proud of the stripes.' },
    { id: 'm_wrong_number', pool: 'mundane', when: ['phoneok'], cooldown: 120, text: 'Your phone rings. A wrong number: a lady asking for "Deborah" about "the casserole situation." You tell her you\'re not Deborah. She says "Well, if you see her." Then hangs up.' },
    { id: 'm_lily_fact', pool: 'mundane', when: ['athome', 'lily == home'], cooldown: 36, texts: ['Lily, from the doorway: "Did you know turtles can breathe through their butts?" She leaves before you can respond. This is how she operates.', 'Lily has drawn a picture of the family. Rick is a small gray cloud in the corner. You don\'t say anything about it.', 'Lily is teaching Sheldon the turtle to read. Sheldon is not a strong student.'] },
    { id: 'm_mom_voice', pool: 'mundane', when: ['mom == work', 'phoneok', 'phase == home'], cooldown: 48, text: 'A voice memo from Mom, 0:07, recorded in what sounds like a supply closet: "Hi baby. Just wanted to hear myself say hi to you. Okay. Bye. Love you."', effects: ['stat.mood +4'] },
    { id: 'm_skyforge_update', pool: 'mundane', when: ['phase == home', 'athome'], cooldown: 72, text: 'Skyforge downloads a 4 GB update that adds one hat.' },
    { id: 'm_library_nap', pool: 'mundane', when: ['loc == library'], cooldown: 48, text: 'A man in the periodicals section is asleep sitting perfectly upright, holding a newspaper from last week. The librarian gently puts a blanket on him. No one says a word.' },
    { id: 'm_diner_regular', pool: 'mundane', when: ['loc == diner'], cooldown: 48, texts: ['A trucker orders "the usual" and Dolores brings him a slice of lemon meringue and a crossword. He\'s been coming here for nineteen years.', 'Two old men are arguing about whether a hot dog is a sandwich. It has clearly been going on since 1987.'] },
    { id: 'm_mall_santa', pool: 'mundane', when: ['loc == mall'], cooldown: 96, text: 'They\'re already putting up the Christmas decorations at the mall. It\'s October. A worker on a ladder looks like she has made peace with nothing.' },

    /* ---------------- phone buzzes while you're doing something else ---------------- */
    { id: 'n_meme', pool: 'notify', when: ['phoneok', 'hour > 8', 'hour < 23'], cooldown: 20, effects: [() => SH.Phone.push('jordan', 'jordan', SH.util.pick(['[image: cat wearing a tiny cowboy hat, captioned "yeehaw but make it sad"]', '[video: a goose chasing a mall cop] BRO', 'mr dale when u ask to use the bathroom: [image: gollum]', 'this is u [image: a raccoon eating grapes very seriously]', '[image: skyforge character clipping through a wall] ME', 'why is this so me [image: a dog falling off a couch in slow motion]']))] },
    { id: 'n_spam', pool: 'notify', when: ['phoneok'], cooldown: 72, effects: ['notify messages|+1 (844) 555-0199|CONGRATS! You\'ve been selected for a FREE cruise!! Reply YES to claim. Msg&data rates may apply.'] },
    { id: 'n_skyforge_daily', pool: 'notify', when: ['phoneok', 'hour > 15'], cooldown: 30, effects: ['notify skyforge|Skyforge|Your daily chest is ready! ⚔️ Don\'t break your 12-day streak!'] },
    { id: 'n_freeze', pool: 'notify', when: [() => SH.weatherDay(SH.day() + 1).lo < 36, 'hour > 14', 'phoneok'], cooldown: 48, effects: [() => SH.Phone.notify('weather', 'Weather alert', 'Freeze warning tonight. Low near ' + SH.weatherDay(SH.day() + 1).lo + '°F. Protect pipes, pets and plants.')] },
    { id: 'n_calendar', pool: 'notify', when: ['phoneok'], cooldown: 12, effects: [() => SH.Phone.calendarPing && SH.Phone.calendarPing()] },
    { id: 'n_low_bat', pool: 'notify', when: ['bat < 20', 'bat > 0'], cooldown: 6, effects: ['notify settings|Battery|20% battery remaining. Low Power Mode?'] },
    { id: 'n_class_chatter', pool: 'notify', when: ['phoneok', 'hour > 15', 'hour < 23', 'phase == home'], cooldown: 10, effects: [() => SH.Phone.push('class', 'class', SH.util.pick(['maddie.k: who stole my pencil case i know it was one of u', 'devonnn: does anyone understand the math hw or are we all just vibing', 'priya.draws: [image: mr dale as a gargoyle, part 2]', 'ava.reads: halloween dance theme is "under the sea" again lmaooo', 'b.rando: my dog ate a sock and now we\'re at the vet at 9pm pray for him', 'kaylee_xo: guys what if the moon was cheese tho']))] },

    /* ---------------- world reactions (rumors, memory) ---------------- */
    { id: 's_okafor_callin', pool: 'mundane', weight: 20, when: ['flag.okaforCallIn', 'loc == school', 'weekday', 'hour > 9', 'hour < 14', 'phase == home'], once: true, title: 'A Note From the Office', text: 'A student aide hands your teacher a pink slip. "Ms. Okafor would like to see ' + '{name}' + '. Now, please." Thirty heads turn.',
      choices: [{ t: 'Go to Room 204', cls: 'safe', effects: [() => SH.Talk.open('okafor', { ctx: 'rumor', turnsMax: 8 })] }] },
    { id: 's_patel_mailbox', pool: 'mundane', weight: 8, when: ['flag.patelWatching', 'athome', 'hour > 15', 'hour < 20'], once: true, text: 'Mrs. Patel catches you at the mailbox. She doesn\'t ask anything. She just presses a Tupperware of dal into your hands and says, "I hear things, dear. My porch light is on all night. All night." Then she goes inside.', effects: ['stat.full +20', 'stat.mood +6', 'flag knowsPatelPorch'] },
    { id: 's_class_whispers', pool: 'mundane', weight: 6, when: ['loc == school', 'weekday', () => SH.Rumor.list().length > 0], cooldown: 48, text: 'Two girls in the hallway stop talking when you walk by. Then start again, quieter. You catch your name. You catch "stepdad." You keep walking like you didn\'t.', effects: ['stat.stress +5'] },
    { id: 's_tyler_revenge', pool: 'mundane', weight: 10, when: ['flag.tylerKnowsYouTold', 'loc == school', 'weekday'], once: true, title: 'Behind the Gym', who: 'tyler', text: 'Tyler corners you by the bike racks. His eyes are red. "You told people. About my dad." He\'s not yelling. That\'s worse.',
      choices: [{ t: '"I\'m sorry. I shouldn\'t have."', cls: 'safe', effects: ['rel.tyler +20', 'flag tylerApology'], text: 'He stares at you. Then he kicks the bike rack, hard, and walks away. The next day he doesn\'t look at you. The day after, he nods. Once.' },
        { t: '"At least my dad isn\'t the one—" (stop)', effects: ['rel.tyler -10', 'stat.stress +8'], text: 'You stop. You both know how the sentence ends. You both know it ends the same for both of you. He walks away without a word.' }] },

    /* ---------------- on the run: the city at night ---------------- */
    { id: 'r_poster', pool: 'run', when: ['flag.__reported'], cooldown: 24, text: 'On a telephone pole: a flyer with your school photo. MISSING. The one where you blinked. Mom must have picked it because it was the only recent one.', effects: ['stat.mood -8', 'stat.stress +6'] },
    { id: 'r_busker', pool: 'run', when: ['loc in bus,mall,park', 'hour > 10', 'hour < 20'], cooldown: 24, text: 'A busker plays "Here Comes the Sun" on a guitar with five strings. Someone drops a dollar. You stand there for the whole song. It\'s warmer than it should be.', effects: ['stat.mood +5'] },
    { id: 'r_sirens', pool: 'run', when: ['dark'], cooldown: 12, text: 'Sirens, far off. Probably nothing to do with you. Your heart doesn\'t know that.', effects: ['stat.stress +4'] },
    { id: 'r_cat_again', pool: 'run', when: ['flag.strayCat', 'outdoor'], cooldown: 36, text: 'A gray cat with a torn ear on a fence. It can\'t be {cat}. It\'s probably not {cat}. You say "hey, {cat}" anyway, and it blinks at you slowly, which in cat means something.', effects: ['stat.mood +6'] },
    { id: 'r_kind_stranger', pool: 'run', when: ['loc in diner,laundromat,bus', 'stat.full < 40'], cooldown: 48, text: 'A woman at the next table pushes half a sandwich toward you without looking up from her phone. "I\'m full," she lies. She leaves before you can say thank you.', effects: ['stat.full +18'] },
  ]);
  // flag mirror so data conditions can read G.reported
  const baseHourly = SH.Engine.hourly;
  SH.Engine.hourly = function (o) { if (SH.G) SH.G.flags.__reported = !!SH.G.reported; baseHourly(o); };
})(window.SH);
(function (SH) {
  const L = { tardy: 'Mr. Dale wrote something down when you came in late.', 'QuikMart called home': 'Raj called the house. Of course he did.', 'school called home': 'The school called home. Mom\'s voice on the phone went very quiet.', 'you mentioned running away': 'Mom heard that. She\'s going to remember it.', 'you posted about leaving': 'People saw your post. Somebody\'s mom follows Chirp.' };
  SH.SUSP_LINE = (why) => L[why] || ('Someone noticed: ' + why + '.');
})(window.SH);
