/* SMALL HOURS — Part 7b: "found" endings that remember your run. They replace the generic ride-home (foundHome) or
   told-the-truth (foundSafe) ending when your run had something specific in it: a motel room, a base, a business,
   runaway kids, a fake ID, a cover name, a disguise, both families on Chirp, a farm, a diner, Halloween, winter, a cold. */
(function (SH) {
  const X = SH.EndX; if (!X) return;
  const H = ['foundHome'], S = ['foundSafe'], HS = ['foundHome', 'foundSafe'];
  const bz = (c) => Object.values(c.g.biz || {}).filter(Boolean).sort((a, b) => b.total - a.total)[0];
  const nlook = (c) => (c.g.look ? Object.values(c.g.look).filter(Boolean).length : 0);
  const cov = (c) => (c.place && (c.g.cover || {})[c.place.id] || {}).name;
  const hp = (c) => c.g.hp || {};
  const safeLine = (c) => (c.base === 'foundSafe' ? ` And because you told Officer Lowe the truth, you don't go back to the house with ${c.rick} in it. Mom meets you somewhere else.` : '');
  const E = (k, on, p, w, t, sub, x) => ({ k, on, p, w, t, sub, x });
  X.add([
    E('fMotel', HS, 3, (c) => !!c.g.room && typeof c.g.room === 'object' && !!c.g.room.n, 'Checkout Time', (c) => `found · ${c.g.room.n}`, (c) => [`The knock on Room ${10 + (c.g.room.n.length % 30)} comes at 7 AM. Not housekeeping. You know before you open the door.`, `${c.g.room.clerk} is behind the officer, twisting a dish towel. "I'm sorry, kid. I'm sorry. I have a daughter." You find out later ${c.g.room.k === 'sloppy' ? 'Stu lost his license over renting to you, and didn\'t complain once' : 'the clerk called because she\'d stopped sleeping, worrying about you'}.`, `The officer lets you shower first. Lets you pack. Lets you take the little soaps. ${safeLine(c)}`]),
    E('fMotel2', HS, 3, (c) => c.g.room && typeof c.g.room === 'object' && c.g.room.how !== 'solo', 'Two Rooms, Side by Side', 'found · a motel, all of you', (c) => [`They find you in the morning: two rooms with the connecting door propped open, ${c.pl} asleep across three beds and a pile of blankets.`, 'The officer counts heads twice and sits down on the edge of a bed, suddenly tired. "Okay. Okay. Everybody\'s here. Everybody\'s okay. That\'s the whole job today."', `The families arrive one by one all afternoon, each hug longer than the last. ${safeLine(c)}`]),
    E('fBase', HS, 3, (c) => c.g.base && (c.g.base.up || []).length >= 2, 'Somebody Built This', (c) => `found · your ${c.g.base.type === 'camp' ? 'camp' : c.g.base.type === 'barn' ? 'hayloft' : 'hideout'}`, (c) => [`The deputy stands in the middle of your base for a long time: the tarp roof, the bedding, the lantern, the bucket with a lid. "You built this?" You nod.`, `"I've seen grown men do worse." She takes pictures, not for evidence. "My kid'll never believe me." She helps you carry the lantern to the car. You insist.${c.n ? ` ${c.pl} carry the rest.` : ''}`, `It's a strange thing, to be proud and caught at the same time. ${safeLine(c)}`]),
    E('fBiz', HS, 3, (c) => bz(c) && bz(c).total >= 40, (c) => `${bz(c).name}: Closed`, 'found · at your business', (c) => [`The cruiser pulls up while there's a line at ${bz(c).name}. The officer waits. He actually waits until you've served everyone, and then buys one himself.`, `"Kid, you've got the best-run operation in ${c.town}," he says. "Also you've been missing for ${Math.max(1, Math.round(c.days))} days." The customers in line try to argue on your behalf. One of them offers to be your lawyer. She's a dentist.`, `The town takes up a collection. It pays for your bus ticket home and there's forty dollars left over, which you split with ${c.n ? c.pl : 'the officer, who refuses it'}. ${safeLine(c)}`]),
    E('fRk', HS, 3, (c) => (c.g.rkids || []).length >= 1, 'Everybody Gets a Blanket', 'found · with the other runaways', (c) => [`When they find you, they find all of you. The officer calls for a van, then a second one. There are more of you than the paperwork expected.`, `Some of you have families pacing at home. Some of you don't, and those are the hardest calls: to a caseworker, a group home, an aunt nobody has talked to in years. You refuse to get in the van until you know where ${c.pn.filter((_, i) => i >= (c.g.party || []).length)[0] || 'everyone'} is going.`, `The officer makes the calls in front of you, on speaker, so you can hear. It's the most respectful thing an adult has done for you in weeks. ${safeLine(c)}`]),
    E('fFakeId', HS, 3, (c) => !!c.g.fakeId, 'Casey Reed, Age 18', 'found · the fake ID', (c) => [`At the station, the officer empties your backpack onto the desk. Out slides a laminated card that says you're ${c.g.fakeId.name}, eighteen years old.`, `${c.mom === 'Mom' ? 'Mom' : c.mom} picks it up. Looks at the photo. Looks at you. Then she starts laughing: really laughing, the helpless kind, until she's crying, and then she's hugging you with the card still in her hand.`, `"Eighteen," she keeps saying into your hair. "Eighteen. You don't even have armpit hair." The officer confiscates the card. Later, much later, she asks for it back, and frames it. ${safeLine(c)}`]),
    E('fCover', HS, 2, (c) => !!cov(c), (c) => `Goodbye, ${cov(c)}`, 'found · the name you used', (c) => [`"Your name's not ${cov(c)}, is it," the deputy says. It isn't a question. The lady from the store is standing behind her, looking betrayed and relieved at the same time.`, `"I told everyone you were visiting your ${c.g.cover[c.place.id].story === 'grandma' ? 'grandma' : 'family'}," the store lady says. "I defended you at church." She hugs you anyway. She smells like peppermints.`, `For a while after you get home, you answer to ${cov(c)} by accident. ${c.mom === 'Mom' ? 'Mom' : c.mom} starts calling you that sometimes, as a joke. It stops being a joke. It becomes something only the two of you share. ${safeLine(c)}`]),
    E('fDisguise', HS, 3, (c) => nlook(c) >= 3, 'I\'d Know You Anywhere', 'found · in disguise', (c) => ['Different hair, different color, different glasses, different clothes. Nobody in three towns recognized you.', `${c.mom === 'Mom' ? 'Mom' : c.mom} recognizes you from the far end of the police station hallway, through a door with wire in the glass, from behind. She's running before the officer can say your name.`, `"Your hair," she says, holding your face. "What did you DO to your hair." Then: "I don't care. I don't care. I'd know you anywhere." ${safeLine(c)}`]),
    E('fChirp', HS, 3, (c) => Object.values(c.g.pw || {}).some((x) => x.chirp), 'Two Families', 'found · everyone was looking', (c) => [`By the time they find you, ${c.pl}'s face is on every Chirp feed in the state, right next to yours. Two missing kids are a news story, and the story has 40,000 shares.`, `At the station, both families are waiting. ${c.pl}'s parent grabs ${c.n === 1 ? 'their kid' : 'the nearest kid'} first, then you, then everyone, a pile of hugs in a hallway.`, `Later, ${c.pl}'s parent sits down next to you. "Thank you for keeping them safe." You didn't expect that. You expected yelling. ${safeLine(c)}`]),
    E('fNote', HS, 2, (c) => Object.values(c.g.pw || {}).some((x) => x.note && x.note.s >= 3), 'The Note on the Pillow', 'found · a note that mattered', (c) => [`${c.pl}'s parent has the note in their coat pocket. They've read it so many times it's soft as cloth.`, '"This is the only reason I slept at all," they tell you, unfolding it with shaking hands. "\'I\'m okay. I\'m with Sam. I love you.\' I read it every hour."', `They look at you for a long time. "You helped write this, didn't you." You nod. They hug you harder than your own family ever has. ${safeLine(c)}`]),
    E('fFarm', HS, 3, (c) => c.g.lessons && c.g.lessons.n >= 3, 'Character Witness', 'found · the farmer came', (c) => [`At the county office, while everyone argues about forms, the door bangs open and in walks the farmer, still in muck boots, with a jar of peaches.`, `"This kid," the farmer tells the social worker, pointing, "mucked my barn for ${c.g.lessons.n} days straight and never complained once. Drives better than my nephew. Whatever's going on at home, you fix it, or I'll be back."`, `The social worker writes that down. All of it. It turns out to matter. ${safeLine(c)}`]),
    E('fDiner', HS, 3, (c) => Object.values(c.g.street || {}).some((x) => x >= 30), 'The Waitress', 'found · the regulars', (c) => ['The waitress from the diner shows up at the station before your family does. She\'s still in her apron. She brought hash browns in a to-go box.', '"I\'m not family," she tells the desk officer. "I\'m the next best thing. I\'m the one who fed this kid for a month." Nobody argues with her.', `She waits until your family comes. She gives your ${c.mom === 'Mom' ? 'mom' : c.mom} a very long look, and a card with her number on it, "in case." ${safeLine(c)}`]),
    E('fHalloween', HS, 4, (c) => SH.World2 && SH.World2.halloween(c.g.t), 'Trick or Treat', 'found · Halloween', (c) => ['They find you on Halloween, in costume, with a pillowcase full of candy.', `The officer takes one look and just starts laughing. "I've been looking for you for ${Math.max(1, Math.round(c.days))} days, and you're out here as ${c.n ? 'a gang of ghosts' : 'a vampire'}." She lets you finish the block. She holds your pillowcase.`, `${c.mom === 'Mom' ? 'Mom' : c.mom} is at the station with a candy bar in each hand, because she didn't know what else to bring. ${safeLine(c)}`]),
    E('fWinter', HS, 3, (c) => SH.World2 && SH.World2.season(c.g.t) === 'winter', 'Frostbite', 'found · in the snow', (c) => ['The snow came early and it didn\'t stop. You were warm for the first half of the night. Then you weren\'t.', 'The snowplow driver sees your footprints going into the bus shelter and not coming out. He radios it in, then sits with you in his cab with the heat on full blast, feeding you gas station coffee with six sugars.', `Your fingers hurt for a week. They heal. You'll never be careless about cold again. ${safeLine(c)}`]),
    E('fSick', HS, 3, (c) => (hp(c).cold || 0) >= 40, 'Chicken Soup', 'found · sick', (c) => ['You\'ve been sick for days. Your nose is raw, your chest rattles, your head is full of wet cement. When the officer finds you, you\'re almost glad.', '"You\'re burning up," she says, and her hand on your forehead is the first cool thing in days. She drives straight to urgent care, lights on, no siren.', `${c.mom === 'Mom' ? 'Mom' : c.mom} brings soup to the urgent care. Real soup, in a thermos, from home. You didn't know you'd missed the taste of home until you tasted it. ${safeLine(c)}`]),
    E('fBlister', HS, 2, (c) => (hp(c).blist || 0) >= 60, 'Two Hundred Miles', 'found · on foot', (c) => [`You walked so far your shoes gave up before you did. When the deputy finds you, you're sitting on a guardrail with your socks off, staring at your feet.`, '"Oh, kiddo," she says. She has a first-aid kit, and she kneels in the gravel and cleans and bandages each blister herself.', `"You walked all this way?" she asks. You nod. "Then you can do anything. Let's do the next part in a car." ${safeLine(c)}`]),
    E('fStreet', HS, 2, (c) => (c.g.watch && Object.keys(c.g.watch).length) || (c.g.excuse && Object.keys(c.g.excuse).length >= 2), 'Keeping an Eye on You', 'found · the officer who noticed', (c) => ['The officer from the stand finds you. The one who said he\'d be keeping an eye on you. He did.', `"School project," he says, deadpan. "Charity. Helping your aunt." He counts your excuses on his fingers. "You're a terrible liar, kid. That's a good thing. Stay that way."`, `He buys you a burger on the way to the station. He tells you about his own dad, briefly, looking at the road. It helps more than you expected. ${safeLine(c)}`]),
    E('fCrush', HS, 3, (c) => c.partnerWith, 'Holding Hands in the Back Seat', 'found · together', (c) => [`They find you and ${c.partnerN} sharing a bag of pretzels on a curb. Twelve years old. Very, very innocent. Very, very in trouble.`, `In the back of the cruiser you hold hands the whole way, and the officer pretends not to see it in the mirror.`, `Both your families are at the station. ${c.partnerN}'s parent looks at your hands, and at you, and sighs the sigh of a parent who has just realized their kid is growing up. ${safeLine(c)}`]),
    E('fBig', HS, 3, (c) => c.n >= 3, 'The Whole Crew', 'found · a big group', (c) => [`${c.n + 1} kids. One officer. She calls for backup mostly so someone can help carry the backpacks.`, `At the station it's chaos: parents, caseworkers, a reporter who gets asked to leave, somebody's grandma handing out granola bars. In the middle of it, ${c.pl} and you sit in a row on a bench, shoulder to shoulder, and don't let go of each other.`, `Whatever happens next, it happens to all of you. That was always the point. ${safeLine(c)}`]),
    E('fLong', HS, 2, (c) => c.days >= 21, 'Twenty-One Days', 'found · three weeks gone', (c) => [`${Math.round(c.days)} days. Long enough that your missing poster faded in the sun. Long enough that the news stopped covering it.`, `Not long enough for ${c.mom === 'Mom' ? 'Mom' : c.mom} to stop. She'd been driving to a different town every weekend, putting up new posters, talking to every gas station clerk in three counties.`, `When they finally bring you in, she's there within the hour. She's lost weight. She's got a map in her car covered in pins. She doesn't let go of your hand for two whole days. ${safeLine(c)}`]),
    E('fSafeBase', S, 4, (c) => c.g.base || c.g.room, 'A Door That Locks', 'found · and heard', (c) => ['You spent weeks building yourself a place with a door that locks. Officer Lowe understands that immediately, without you explaining.', `"You don't have to go back to a house where you felt you needed that," she says. "Let's find you somewhere with a lock that someone else is responsible for." It takes a while. It happens.`, `The place they find for you has a lock on the bedroom door, on the inside. The first night, you lock it and unlock it eleven times, just because you can. Then you sleep.`]),
  ]);
})(window.SH);
