/* SMALL HOURS — Part 2c: endings for everything that can happen on the road (travel3 + junkyard + lessons).
   Honest about danger, never glamorous, and every one ends near a safe adult. Group variants outrank solo ones. */
(function (SH) {
  const X = SH.EndX; if (!X) return;
  const to = (c) => (c.extra && c.extra.to && c.extra.to.name) || 'the next town';
  const veh = (c) => (c.veh && c.veh.n) || 'car';
  const g2 = (c) => c.n > 0;
  X.add([
    { k: 'crash', on: ['crash'], p: 2, w: g2, t: 'Fender, Bender', sub: (c) => `the ${veh(c)} · with ${c.pl}`, x: (c) => [`A curve comes faster than it should. The ${veh(c)} slides, bumps and stops against a fence post with a crunch that sounds much worse than it is. Everyone's okay. ${c.pn[0]} laughs, then cries, then laughs again.`, `The farmer who owns the fence comes out in slippers with a flashlight. He counts heads, counts again, and says "none of you is old enough to drive that," in a voice with no anger in it at all.`, `He makes cocoa while you wait for the deputy. When she comes, he tells her you were "real polite about my fence."`] },
    { k: 'crash', on: ['crash'], p: 1, t: 'Fender, Bender', sub: (c) => `the ${veh(c)}`, x: (c) => [`The ${veh(c)} kisses a guardrail at twenty miles an hour. The airbag doesn't go off, because the airbag was sold for parts in 2019. Your forehead finds the steering wheel.`, 'A woman in a minivan stops, then another car, then a trooper. The trooper looks at the car, then at you, then at the car again. "Where did you even GET this?"', 'You get stitches, three of them. The nurse lets you pick the color of the bandage. Mom arrives at 2 AM and says nothing about the car, only "your head, your head," over and over.'] },
    { k: 'crashDitch', on: ['crashDitch'], p: 1, t: 'The Ditch', sub: 'a county road at night', x: (c) => [`Two wheels drop off the edge of the road and the ${veh(c)} tips gently, almost politely, into the ditch. It stays there, headlights pointed at the sky.`, `You${c.withYou} climb out the passenger side. Nobody's hurt. A tow truck driver named Dot finds you twenty minutes later and doesn't call anyone until she's made sure you've all got her spare jackets on.`, '"I was fifteen, first time I put a truck in a ditch," she says. "Fifteen\'s still too young, and so\'s whatever you are." The sheriff comes. Dot waits with you.'] },
    { k: 'crashHurt', on: ['crashHurt'], p: 1, t: 'Rain on the Windshield', sub: 'what driving at twelve actually costs', x: (c) => ['The rain makes the road look like a mirror. The car doesn\'t stop when you ask it to.', `You wake up in an ambulance with a paramedic holding your hand. Your arm is broken in two places.${c.n ? ` ${c.pn[0]} is in the next ambulance, awake, asking about you.` : ''}`, `It heals. It takes eight weeks and a cast everyone at school signs. What doesn't heal as fast is ${c.mom}'s face in the hospital doorway, and the way you both finally talk, because there's nothing else to do in a hospital but talk.`] },
    { k: 'driveStop', on: ['driveStop'], p: 2, w: (c) => c.skill('drive') >= 60, t: 'License and Registration', sub: 'you drove well. That wasn\'t the problem.', x: (c) => ['You signal. You stay at exactly the speed limit. You check your mirrors like the farmer taught you. The trooper pulls you over anyway, because the driver\'s head barely clears the steering wheel.', '"Honestly? Best driving I\'ve seen all week," she says. "You\'re also about twelve." She calls it in, then buys you a burger at the truck stop while you wait.', `She asks who taught you. You tell her about the farm. She writes that down too, like it matters. Later, a social worker says it does: it means somebody out there was being good to you.`] },
    { k: 'driveStop', on: ['driveStop'], p: 1, t: 'License and Registration', sub: 'blue lights in the mirror', x: (c) => [`The ${veh(c)} weaves. Not much. Enough. Blue lights bloom in the mirror and your whole body goes cold.`, `The trooper's flashlight finds a kid in the driver's seat${c.n ? ' and more kids in the back' : ''}. "Oh, for— okay. Engine off. Everybody's fine. Nobody's in trouble except maybe whoever sold you this."`, 'The ride to the station is in the back of a cruiser. It smells like coffee and old vinyl. She lets you keep the window cracked.'] },
    { k: 'outOfGas', on: ['outOfGas'], p: 1, t: 'Empty', sub: 'the needle said so', x: (c) => [`The ${veh(c)} coughs, sputters and rolls to a stop on a road with no lights in either direction.`, `You walk${c.withYou} two miles to a farmhouse with one lit window. The woman who answers takes one look and says "Well, you'd better come in, the lot of you."`, 'She feeds you, lets you call someone, and waits on the porch with you until headlights come up the road.'] },
    { k: 'van', on: ['van'], p: 1, t: 'Twelve Nights in a Van', sub: (c) => `the ${veh(c)}`, x: (c) => [`By the twelfth night in the ${veh(c)}, the windows have your handprints on them and the seats have learned the shape of you.`, 'A man walking his dog knocks on the glass at 7 AM. He\'s seen the van every morning for a week. He isn\'t angry. He\'s worried, which is worse.', `"I've got a daughter," he says. "If she was sleeping in a van, I'd want somebody to knock." The police officer who comes is gentle. The van gets towed. ${c.n ? 'Your friends hold your hands in the cruiser.' : 'You watch it go through the back window.'}`] },
    { k: 'dog', on: ['dog'], p: 1, t: 'Good Dog', sub: 'a farm road, a big dog', x: (c) => ['A dog the size of a pony comes out of a farmyard barking. You freeze, like you\'re supposed to. It stops a foot away and sniffs your hand, then sits down on your foot.', 'Its owner comes running. "Duke! DUKE. Sorry, he thinks everybody\'s his." Then she looks properly at you. At your backpack. At how far you are from anywhere.', `"Where are you walking to, sweetheart?" The dog leans on your legs. You tell her more than you meant to. She has a phone, a kitchen, and a sister who is a school counselor two towns over.`] },
    { k: 'storm', on: ['storm'], p: 1, t: 'The Storm', sub: 'no roof in sight', x: (c) => ['The storm comes across the fields like a wall. Lightning close enough to hear the crack before the thunder.', `You${c.withYou} run for the only building in sight: a volunteer fire station. The volunteers are there because of the storm. They wrap you in foil blankets that crinkle every time you breathe.`, 'The chief radios the sheriff, then sits with you and tells you terrible jokes until the storm passes and the cruiser comes.'] },
    { k: 'lostWoods', on: ['lostWoods'], p: 1, t: 'Where the Trail Ends', sub: 'the woods', x: (c) => ['The shortcut through the woods stops being a trail and starts being trees. The sun goes behind them faster than you expected.', 'You do the thing from the TubeYou video: stop, stay put, stay warm. You make noise every few minutes. It\'s the longest night of your life.', `At dawn you hear a dog, then voices calling your name, your actual name, from a search line of volunteers in orange vests. The first person to reach you is crying. So are you.`] },
    { k: 'riverCold', on: ['riverCold'], p: 1, t: 'Cold Water', sub: 'the river crossing', x: (c) => ['The bridge is out, so you try the shallow part. It isn\'t shallow. The cold punches the air out of your chest.', `You get out, somehow, soaked and shaking so hard your teeth hurt. A fisherman on the bank gets you into his truck and blasts the heat.`, 'At the ER they call it mild hypothermia. You call it the moment you realized you could have died over a shortcut. Mom arrives with a blanket from home. It smells like home. You didn\'t expect that to matter.'] },
    { k: 'scooterFall', on: ['scooterFall'], p: 1, t: 'Road Rash', sub: 'the scooter', x: (c) => ['A crack in the asphalt catches the wheel and the ground comes up fast. Palms, knees, chin.', 'A crossing guard and a mail carrier both reach you at the same time and argue about who gets to help. The mail carrier wins. She has a first-aid kit in the truck.', 'She asks the questions gently while she cleans the gravel out of your hands, and by the time the bandages are on, she has the whole story, and a phone number to call.'] },
    { k: 'escootDead', on: ['escootDead'], p: 1, t: 'Zero Percent', sub: 'the e-scooter', x: (c) => ['The battery dies eight miles from anywhere. E-scooters are heavy when they\'re dead. Very heavy.', 'You push it along the shoulder until a highway maintenance truck pulls over. The worker has a daughter your age and a charger that doesn\'t fit.', `"I can't leave you out here," he says. "I just can't." He drives you to ${to(c)}, straight to the sheriff's office, and carries the scooter in for you.`] },
    { k: 'bikeLong', on: ['bikeLong'], p: 1, t: 'Mile Twenty', sub: 'the bike', x: (c) => ['Your legs give out at mile twenty. Not tired. Done. You lie down in the grass by the road with the bike on top of you.', 'A cyclist in a very serious outfit stops. "You okay?" You aren\'t. She gives you her electrolyte drink and her energy gel, which tastes like strawberry glue.', 'She rides beside you at walking pace to the next gas station, and makes the call there, and stays.'] },
    { k: 'walkHighway', on: ['walkHighway'], p: 1, t: 'The Shoulder', sub: 'walking the highway at night', x: (c) => ['Trucks pass close enough to shake you. The shoulder is narrow and full of glass.', 'A state trooper pulls over with the lights on but the siren off. "Hop in, please. You\'re going to get killed out here, and I\'d really rather you didn\'t."', 'In the car she turns the heat up and gives you her granola bar. She doesn\'t ask why until you\'ve stopped shaking.'] },
    { k: 'farm', on: ['farm'], p: 1, t: 'The Spare Room', sub: 'never found · a farm at the end of a gravel road', x: (c) => [`${(c.extra && c.extra.farmer) || 'The farmer'} kept every promise, including the hard ones. The county came. The social worker came. There were meetings, and papers, and a judge with reading glasses who asked you what you wanted, and actually listened.`, `You stayed. Kinship foster placement, the paper said. "Home," the farmer said, the first time you came back from school to find your name painted on a mailbox.${c.n ? ` ${c.pl} visited every summer.` : ''}`, 'Years later you can drive anything with wheels, fix most of it, and you still wake up at five without an alarm. Your family never found you, because you stopped being lost. It isn\'t the ending you ran toward. It\'s the one that caught you.'] },
  ]);
})(window.SH);
