/* SMALL HOURS — Part 7a: never-found endings ('gone'), plus health endings (fever, exhaust).
   Triggered by "Disappear for good" (notfound.js). Chosen by what your run actually looked like: base, motel, business,
   group, cover, disguise, the town, the season. Bittersweet on purpose: every one of them costs something. */
(function (SH) {
  const X = SH.EndX; if (!X) return;
  const g = (c) => c.g, B = (c) => c.g.base, bz = (c) => Object.values(c.g.biz || {}).filter((x) => x && x.kind).sort((a, b) => b.total - a.total)[0];
  const cov = (c) => (c.place && (c.g.cover || {})[c.place.id] || {}).name;
  const as = (c) => (cov(c) ? `"${cov(c)}"` : 'a kid with a different name');
  const grp = (c) => (c.n ? ` ${c.pl} ${c.n === 1 ? 'was' : 'were'} there for all of it.` : '');
  const tail = (c) => `Your ${c.mom === 'Mom' ? 'mom' : c.mom} never found you. Some nights that's the saddest sentence you know. Some nights it's the reason you're okay.`;
  const E = (k, p, w, t, sub, x) => ({ k, on: ['gone'], p, w, t, sub, x });
  X.add([
    E('goneEdgeHouse', 1, null, 'The House on the Edge of Town', (c) => `never found · ${c.town}`, (c) => [`Mrs. Albright was eighty-one and lived in the last house before the fields: yellow siding, a porch swing, a garden gone to seed. She'd seen you walk past every day for three weeks. On the twenty-second day she left a plate of cookies on the porch rail with a note: "For whoever needs these."`, `By winter you were raking her leaves. By spring you had a room with a quilt her mother made. She called you ${as(c)} and never once asked what your real name was.${grp(c)}`, `She told the county, eventually, the right way, and fought for you like a lion in orthopedic shoes. When she died you were nineteen, and you read the eulogy, and the whole town came. ${tail(c)}`]),
    E('goneCamp', 3, (c) => B(c) && B(c).type === 'camp' && B(c).up.length >= 4, 'The Clearing', 'never found · the forest camp', (c) => [B(c).shack ? `The shack got better every week: a log frame, walls woven out of branches, a tin roof that sang in the rain, a door that latched from the inside. The farmer down the road stopped asking whose kid you were and started leaving boards by the fence.${grp(c)}` : `The camp got better every week: a tarp roof, a real bed, a lantern that made the pines glow. You learned which mushrooms not to touch, how to hang food from a branch, how to tell rain from wind by the sound.${grp(c)}`, `In March a ranger named Tomás found it. He didn't call anyone that day. He came back the next day with a thermos, and the day after that with a form for a youth conservation program that had housing, school, and no questions it didn't need to ask.`, `You're a ranger now. There's a clearing in your district you check every spring, just in case. ${tail(c)}`]),
    E('goneBuilding', 3, (c) => B(c) && B(c).type === 'building' && B(c).up.length >= 4, 'The Laundromat', 'never found · the abandoned building', (c) => [`The old laundromat had curtains now, a padlock, a heater that ran off a solar panel on the roof. The neighborhood kids called it "the clubhouse" and never told a single adult. Kids are good at that.${grp(c)}`, `A woman from the church across the street figured it out in January. Instead of calling anyone, she bought the building. Instead of kicking you out, she turned it into a drop-in center and hired a real social worker, and let you choose, every single step.`, `The sign over the door still says WASH & FOLD. It's the first thing you look at in the morning. ${tail(c)}`]),
    E('goneBarn', 3, (c) => B(c) && B(c).type === 'barn' && B(c).up.length >= 3, 'The Hayloft', 'never found · the old barn', (c) => [`The barn belonged to a widower named Earl who hadn't been up to the hayloft in eleven years. His knees wouldn't allow it. When he finally climbed up, in April, looking for a ladder, he found a bed, a lantern, a bucket of apples, and ${c.n ? 'a group of kids' : 'a kid'} frozen like deer.`, `"Well," Earl said. "You'd better come have breakfast. Barn's cold." It was the first of about four thousand breakfasts.${grp(c)}`, `Earl taught you to fix fences, drive the tractor, and wait out a storm. He left you the barn. You still sleep in the loft some summer nights, for old times' sake. ${tail(c)}`]),
    E('goneMotel', 3, (c) => c.g.room && typeof c.g.room === 'object' && c.g.room.k !== 'pro', 'Room 14', (c) => `never found · ${c.g.room.n}`, (c) => [`${c.g.room.clerk} stopped charging you for the room in the second month. "You fold towels faster than my nephew," was the explanation. You folded towels, restocked soap, learned to fix an ice machine with a butter knife.${grp(c)}`, `The motel was full of people passing through, and nobody ever looks at a kid who works there. People look through the kid who works there, which turned out to be the best disguise of all.`, `When ${c.g.room.clerk} retired, ${c.g.room.n} got a new owner: you. The vacancy sign still flickers. You never fixed it. ${tail(c)}`]),
    E('goneStand', 3, (c) => bz(c) && bz(c).total >= 120, (c) => bz(c).name, 'never found · a small business', (c) => [`${bz(c).name} started as a folding table and a hand-painted sign. By November the whole town knew it. People came for the ${bz(c).kind === 'lemonade' ? 'cocoa' : 'service'} and stayed to talk. Nobody asks where "the ${bz(c).name} kids" came from. They're just from here now.${grp(c)}`, `The Hendersons from the church took you in "temporarily," then permanently, then legally, with a judge who had bought something from ${bz(c).name} the week before.`, `It's a real storefront now, on Main Street. There's a framed dollar by the register: the first one. ${tail(c)}`]),
    E('goneFix', 4, (c) => bz(c) && bz(c).kind === 'fix' && bz(c).total >= 80, 'Chain Grease', 'never found · the fix-it table', (c) => [`An old man with a bike shop two blocks over watched your fix-it table for a week before he came over. "You're doing that derailleur wrong," he said, and showed you how to do it right.`, `By Christmas you were sweeping his shop. By spring you were fixing bikes in the back. He had a spare room and a daughter who was a family lawyer, which turned out to matter a lot.`, `His name is still on the sign. Yours is under it, smaller. ${tail(c)}`]),
    E('goneRk', 3, (c) => (c.g.rkids || []).length >= 1, 'Found Family', 'never found · together', (c) => [`${c.pl}. Nobody ever looked for some of you, and nobody ever found the rest of you. You made your own kind of family out of the leftover pieces.`, 'It was hard. It was cold, then less cold. Somebody always had a charger, and somebody always stayed awake. When one of you got sick, the others went to the free clinic and lied beautifully.', `Years later, you all still have a group chat. It's called "the base." Every Thanksgiving you rent a cabin and cook a terrible turkey. ${tail(c)}`]),
    E('goneFriends', 2, (c) => (c.g.party || []).length >= 1 && !(c.g.rkids || []).length, 'Two Kids Who Didn\'t Go Back', 'never found · with your friends', (c) => [`It's harder to vanish with a friend. Two missing kids is a news story. You did it anyway: new names, new haircuts, a town where you were "the cousins."`, `${c.pl} went home, eventually, when ${c.n === 1 ? 'they were' : 'everyone was'} ready: a phone call, a bus ticket, a very long hug in a very small kitchen. You didn't. You couldn't. ${c.pl} never told anyone where you were. Not once. Not even when it was hard.`, `You still talk every week. The friendship survived everything. ${tail(c)}`]),
    E('goneCover', 2, (c) => cov(c) && ((c.g.look && Object.values(c.g.look).filter(Boolean).length) || 0) >= 2, 'A Different Name', (c) => `never found · "${cov(c)}"`, (c) => [`You told ${c.town} your name was ${cov(c)}. You said it so many times it stopped feeling like a lie. Your haircut was different, your clothes were different, your walk was different.`, `Years later you pass your own old missing poster, faded, in a gas station on the interstate. You stand in front of it for a long time. The girl at the register asks if you're okay. You say yes. It's almost true.`, `Everyone who loves you now calls you ${cov(c)}. ${tail(c)}`]),
    E('goneDisguise', 2, (c) => ((c.g.look && Object.values(c.g.look).filter(Boolean).length) || 0) >= 4, 'The Supermarket', 'never found · unrecognized', (c) => ['Two years later, in a supermarket three counties from home, you see your mom. She\'s in the cereal aisle. She looks older. She looks right at you.', 'And she doesn\'t know you. Different hair, different glasses, different height, a different way of standing. She says "excuse me, hon" and reaches past you for the oatmeal.', `You go out to the parking lot and sit on the curb for an hour. That night you write her a letter. You don't send it. You write one every year. ${tail(c)}`]),
    E('goneCoast', 3, (c) => c.place && c.place.id === 'p2', 'Low Tide', 'never found · Port Aldine', (c) => ['Port Aldine smells like salt and diesel. The fishing families there have seen a lot of kids come through, and they have a way of not asking.', `The Nguyens ran a crab boat and needed a deckhand small enough to fit in the bait locker. They paid in cash, dinner, and a bunk on the boat that rocked you to sleep better than any bed ever had.${grp(c)}`, `You got your captain's license at twenty-two. The boat is called the Small Hours. Nobody ever asks why. ${tail(c)}`]),
    E('goneCity', 2, (c) => c.tier === 'city', 'Nine Million Strangers', (c) => `never found · ${c.town}`, (c) => [`In ${c.town}, nobody looks at anybody. It was the loneliest year of your life and also the safest.`, 'A drop-in center that didn\'t make you give your real name. A library card under a fake one. A GED program that started at sixteen and didn\'t check very hard. An emancipation hearing at seventeen that you walked into alone and walked out of free.', `You still live in the city. You volunteer at the drop-in center on Tuesdays. You always know the new kids by the way they hold their backpacks. ${tail(c)}`]),
    E('goneDiner', 3, (c) => Object.values(c.g.street || {}).some((x) => x >= 30), 'The Usual', 'never found · the diner', (c) => [`She'd been pouring your water for a month without asking. One night at closing she sat down across from you in the booth and said: "I've got a couch, a cat, and no patience for nonsense. You want the couch?"`, `You took the couch. Then the spare room. Then a job bussing tables at fourteen and a waitressing apron at sixteen.${grp(c)}`, `She's retired now. You run the diner. Every runaway who comes in gets hash browns, no charge, and a very long look over the counter. ${tail(c)}`]),
    E('goneWinter', 2, (c) => SH.World2 && SH.World2.season(c.g.t) === 'winter', 'After the Snow', 'never found · you survived the winter', (c) => ['There was a week in January when you thought you wouldn\'t make it. The cold was a living thing. You slept in your coat and woke up with frost on the inside of the window.', `But winter ends. It always does. In March a family from the church found you ${c.n ? 'all ' : ''}shoveling their walk for five dollars, and invited you in for soup, and kept inviting you.`, `Every first snow, you stand outside with your face turned up, just to feel it and know you're warm inside. ${tail(c)}`]),
    E('goneHalloween', 4, (c) => SH.World2 && SH.World2.halloween(c.g.t), 'All Hallows', 'never found · Halloween night', (c) => ['You disappeared for good on Halloween. You walked out of town in a costume, one kid among a thousand, and nobody looked twice.', 'The bus driver thought you were going to a party. The woman at the next town\'s church thought you were a trick-or-treater who got lost. She was very kind about it, and very kind for the next six years.', `You still dress up every Halloween. Not as anything scary. As yourself, the way you were at twelve: a hoodie, a backpack, a face nobody recognized. ${tail(c)}`]),
    E('goneLibrarian', 1, (c) => c.tier === 'town' || c.tier === 'small', 'Overdue', (c) => `never found · the ${c.town} library`, (c) => [`You read every book in the ${c.town} library's young adult section in six weeks. The librarian, Ms. Faye, noticed, because librarians notice everything.`, 'She got you a library card under a name you made up on the spot. Then a job shelving books. Then, when she finally asked and you finally told her, a room in the apartment above the library that nobody had used since the eighties.', `You're the librarian now. You have a rule: any kid can sit anywhere, all day, as long as they're reading. Actually reading. ${tail(c)}`]),
    E('goneOrchard', 1, (c) => c.tier === 'village', 'The Orchard', (c) => `never found · outside ${c.town}`, (c) => [`The orchard was run by a bunch of old hippies who had been growing apples since before your mom was born. They didn't have a TV. They didn't read the news. They did have a bunk room for pickers and an extra bowl at every meal.`, `You picked apples in the fall, pruned in the winter, and learned the names of forty-one varieties.${grp(c)} Nobody ever asked for a last name. They didn't use theirs either.`, `The orchard is a co-op now, and you're on the board. The Honeycrisps are your fault. ${tail(c)}`]),
    E('goneLetter', 1, null, 'Eighteen', 'never found · until you decided', (c) => ['On your eighteenth birthday you bought a stamp.', `The letter took you three weeks to write and it was one page long. It said where you'd been, and that you were okay, and some things about ${c.rick} that you'd never said out loud, and some things about ${c.mom === 'Mom' ? 'Mom' : c.mom} that were harder to say because they were kind.`, 'She drove eleven hours the day it arrived. You met at a diner halfway. Neither of you ate anything. You talked until they closed. You were never found. You came back on your own, which is a different thing, and it\'s yours.']),
    E('gonePostcards', 1, null, 'Postcards', 'never found · but not silent', (c) => ['Every year on your birthday, a postcard arrived at your mom\'s house. No return address. A different postmark every time. Just four words: "I\'m okay. Love you."', `She kept every one of them on the refrigerator. Eventually the refrigerator was more postcard than refrigerator.`, 'When you finally came home, at twenty, she had them in a shoebox on the kitchen table, and she\'d written the date she got each one on the back. That\'s how you knew she never stopped waiting. That\'s how she knew you never stopped thinking about her.']),
    E('goneLighthouse', 2, (c) => c.place && /coast|shore|harbor|bay/.test(c.place.biome || ''), 'The Keeper', 'never found · the lighthouse', (c) => ['The lighthouse had been automated for thirty years, but Mr. Halvorsen still lived in the keeper\'s cottage because nobody had the heart to make him leave.', `He needed someone to climb the 114 stairs to check the lamp. His knees didn't. You did.${grp(c)}`, `He taught you knots, tides, and chess, and died when you were twenty with the whole town at the funeral. The cottage is yours now. You still climb the stairs every night, for no reason at all. ${tail(c)}`]),
    E('goneFair', 1, (c) => SH.World2 && SH.World2.season(c.g.t) !== 'winter' && c.days > 30, 'The Traveling Fair', 'never found · on the road', (c) => ['The Kowalski family ran the ring toss and the funnel cake stand and had been on the road with the county fair circuit for three generations. They had five kids of their own and didn\'t notice a sixth for about a week.', 'When they did, Grandma Kowalski just sighed and set another plate. You learned to run the ring toss, count change fast, and sleep in a moving truck.', `The fair still comes through your hometown every August. Every year you run the ring toss and watch the crowd, and every year you don't see her, and you don't know if you're relieved. ${tail(c)}`]),
    E('goneChurch', 1, (c) => c.tier === 'small' || c.tier === 'village', 'Sanctuary', (c) => `never found · ${c.town}`, (c) => [`Pastor Ruth found you asleep in the back pew on a Tuesday. She didn't call anyone. She brought a blanket and a sandwich and sat three pews up so you wouldn't feel crowded.`, `It took a month before you talked. It took a year before the paperwork was right: a guardianship, a real school, a room in the parsonage with a window that looks at the bell tower.${grp(c)}`, `You still aren't sure what you believe. You're sure about Ruth. ${tail(c)}`]),
  ]);
  X.add([
    { k: 'fever', on: ['fever'], p: 1, t: '103.4°', sub: 'too sick to keep going', x: (c) => ['The cold turned into something worse. You were shivering and sweating at the same time, and the ground kept tilting.', `${c.n ? c.pl + ' ran for help.' : 'You don\'t remember walking into the gas station. You remember the floor, cool against your cheek.'} Then an ambulance ceiling, a paramedic saying "stay with me, buddy," the prick of an IV.`, `Pneumonia. Four days in a hospital bed. ${c.mom === 'Mom' ? 'Mom' : c.mom} slept in the chair next to you all four nights, and when you woke up the first thing she said was "you're too thin," and the second thing was "I'm listening. Tell me."`] },
    { k: 'fever', on: ['fever'], p: 2, w: (c) => c.tier === 'village', t: 'The Country Doctor', sub: 'a fever in a small place', x: (c) => ['In a village, the doctor still makes house calls. Or barn calls. Or "that kid sleeping behind the feed store" calls.', 'Dr. Okafor had a black bag and a voice like warm bread. She took your temperature, said a word you didn\'t know, and carried you to her car herself.', 'She sat with you at the county hospital until your mom came, and then she stayed a little longer, and asked your mom some questions in the hallway in a very quiet, very firm voice.'] },
    { k: 'exhaust', on: ['exhaust'], p: 1, t: 'Running on Empty', sub: 'days without real sleep', x: (c) => ['You haven\'t slept properly in four days. The world has gone gray and slow at the edges. You sit down on a bench to rest your eyes for one second.', 'You wake up to a police officer gently shaking your shoulder. It\'s dark. You slept for nine hours on a bench in the open. Anyone could have found you. Someone did, and it was the right someone.', `"When did you last sleep in a bed?" she asks. You can't remember. She drives you somewhere with a bed. You sleep for fourteen hours. When you wake up, ${c.mom === 'Mom' ? 'Mom' : c.mom} is there.`] },
    { k: 'exhaust', on: ['exhaust'], p: 2, w: (c) => c.n > 0, t: 'The Last One Awake', sub: 'nobody slept', x: (c) => [`None of you had slept right in days. ${c.pl} fell asleep sitting up at a bus shelter. You tried to keep watch and couldn't.`, 'A night-shift nurse walking to her car found you all in a heap under one blanket. She didn\'t call the police first. She called the diner across the street, and the diner sent out four cocoas, and THEN she called.', 'You were all home by morning. Every family. Every kitchen. Every "we\'re not angry, we were so scared."'] },
  ]);
})(window.SH);
