/* SMALL HOURS — Part 7d: more endings. Extra never-found endings (by place, biome, season, group) and more "found"
   variants tied to specific moments from Parts 2–6 (a clerk's phone call, a caught fake ID, a parent you told the town to,
   an exposed fake charity, the diner after a creep, a comfort talk, the kid you walked home...). */
(function (SH) {
  const X = SH.EndX; if (!X) return;
  const HS = ['foundHome', 'foundSafe'];
  const mom = (c) => (c.mom === 'Mom' ? 'Mom' : c.mom);
  const tail = (c) => `Your ${c.mom === 'Mom' ? 'mom' : c.mom} never found you. You think about her every day. You're okay. Both of those are true.`;
  const grp = (c) => (c.n ? ` ${c.pl} ${c.n === 1 ? 'stayed' : 'stayed too'}.` : '');
  const safeLine = (c) => (c.base === 'foundSafe' ? ' And because you told the truth, you don\'t go back to that house.' : '');
  const bio = (c, re) => !!(c.place && re.test(c.place.biome || ''));
  const G = (k, p, w, t, sub, x) => ({ k, on: ['gone'], p, w, t, sub, x });
  const F = (k, p, w, t, sub, x) => ({ k, on: HS, p, w, t, sub, x });
  X.add([
    G('goneMountain', 2, (c) => bio(c, /mountain|hill|ridge|pine|forest/), 'Above the Tree Line', 'never found · the mountains', (c) => ['The ski lodge needed someone to fold rental jackets and didn\'t ask questions of anyone who could fold fast. The owner\'s family lived in the back and had a kid your age who needed a friend more than anything.', `You learned to ski by falling down the bunny hill four hundred times.${grp(c)} By sixteen you were teaching it.`, `The mountain doesn't care who you were. That was the best thing about it. ${tail(c)}`]),
    G('goneRiver', 2, (c) => bio(c, /river|lake|valley|wetland/), 'Houseboat', 'never found · on the river', (c) => ['Old June lived on a houseboat that hadn\'t moved in twenty years, tied to a dock that was mostly rust. She fished every morning and needed someone to hold the net.', `The river rocked you to sleep. June taught you to read the water, gut a fish, and play cribbage badly.${grp(c)}`, `When she moved to a home, she gave you the boat, and a sealed envelope with papers inside that made it all legal. She'd been planning it for years. ${tail(c)}`]),
    G('goneDesert', 2, (c) => bio(c, /desert|dry|plain|prairie|grass/), 'Big Sky', 'never found · the plains', (c) => ['Out on the plains, the sky is so big it makes your problems look like specks. A ranching family out past the last paved road took you on for the calving season.', `You learned to ride a horse, fix a windmill, and sit still enough that the coyotes forgot you were there.${grp(c)}`, `You never went back east. The sky out here is the only roof you ever really wanted. ${tail(c)}`]),
    G('goneFarmland', 2, (c) => bio(c, /farm/) && !(c.g.lessons && c.g.lessons.n >= 3), 'Harvest', 'never found · farm country', (c) => ['Harvest season needs every pair of hands, and nobody checks the paperwork of a kid who can drive a grain cart in a straight line.', `The Lindqvists had four kids already. "What's five," Mrs. Lindqvist said, and that was that.${grp(c)}`, `You still smell diesel and cut wheat and feel like you're home. ${tail(c)}`]),
    G('goneSmallTown', 1, (c) => c.tier === 'small', 'Main Street', (c) => `never found · ${c.town}`, (c) => [`${c.town} had one stoplight, two churches, and a hardware store that needed a kid to sweep up. By Christmas everybody knew you. Nobody knew where you came from. In a town that small, that's almost impossible, and they did it anyway, on purpose, together.`, `It was the kind of town where the whole place quietly decides to protect someone.${grp(c)} The sheriff played cards with the hardware store owner every Thursday and never once asked about the new kid.`, `You married someone from ${c.town}, eventually. Everyone came. ${tail(c)}`]),
    G('goneTown', 1, (c) => c.tier === 'town', 'The Apartment Over the Bakery', (c) => `never found · ${c.town}`, (c) => [`The bakery on the corner started at 4 AM, and the baker needed someone who didn't mind the hours. You didn't mind anything, as long as it was warm.`, `The apartment upstairs smelled like bread all the time. Mrs. Kowalczyk taught you to braid challah and say "not bad" in Polish, which was her highest compliment.${grp(c)}`, `You never lost the early-morning habit. You like being awake while the town sleeps. It still feels like a secret. ${tail(c)}`]),
    G('goneVillage', 1, (c) => c.tier === 'village', 'Two Hundred People', (c) => `never found · ${c.town}`, (c) => [`${c.town} had two hundred people and most of them didn't have internet. The ones who did didn't care about missing kids from far away. You were just "the new kid at the Hansens'."`, `The Hansens were old and their own kids had moved to the city. They needed help with the chickens. You needed chickens, it turned out.${grp(c)}`, `When you finally told them the truth, years later, Mr. Hansen just nodded. "Figured," he said. "Didn't matter." ${tail(c)}`]),
    G('goneBase5', 4, (c) => c.g.base && c.g.base.up.length >= 7, 'Built It Yourself', 'never found · the base that became a house', (c) => [`Your base got a heater, a padlock, a solar panel, curtains, a real bed. At some point it stopped being a hideout and started being a home, and you didn't notice when.${grp(c)}`, 'The land turned out to belong to a land trust that nobody visited. When they finally did, the woman from the trust looked at what you\'d built for a long time and said, "Would you like a job as a caretaker?"', `You still live there. The heater still works. You still lock the padlock at night, out of habit, and then unlock it, because you can. ${tail(c)}`]),
    G('goneWholeGroup', 4, (c) => c.n >= 3, 'The Commune of Five Kids', 'never found · all of you', (c) => [`${c.pl} and you. Too many to hide, everybody said. They were wrong.`, 'You split into "cousins," "siblings," "neighbors" in three different families in the same small town. You saw each other every day at school, and nobody ever connected it.', `On your twenty-first birthdays you all got matching tattoos of the base's lantern. ${tail(c)}`]),
    G('goneSpring', 2, (c) => SH.World2 && SH.World2.season(c.g.t) === 'spring', 'Mud Season', 'never found · spring', (c) => ['You made it through the winter. That was the hard part. Spring was mud and robins and a garden center that needed someone to water flats of tomato seedlings.', `The owner paid cash and asked no questions and, by June, had given you the key to the greenhouse and the room above it.${grp(c)}`, `You can grow anything now. You think maybe you grew yourself, too. ${tail(c)}`]),
    G('goneLong', 3, (c) => c.days >= 60, 'Sixty Days', 'never found · two months and counting', (c) => [`After sixty days, the search stops being a search and starts being a file. Your poster comes down at the gas station. Someone else's goes up.`, `That was the day you stopped looking over your shoulder.${grp(c)} Life got small and quiet: work, sleep, a library book, a friend.`, `Quiet turned out to be the thing you'd been running toward the whole time. ${tail(c)}`]),
    G('goneCrush', 3, (c) => c.partnerWith, 'Pen Pals', 'never found · you and your best person', (c) => [`${c.partnerN} went home after a month, because you made ${c.partnerN} go. Somebody had to be okay. You stayed gone.`, `But every week, a letter. Real paper, a PO box, no return address on yours. ${c.partnerN} told nobody. Not once. For six years.`, `When you were eighteen, you met at a coffee shop halfway. ${c.partnerN} brought the letters, all of them, in a shoebox. You brought yours. ${tail(c)}`]),
  ]);
  X.add([
    F('fClerkCall', 3, (c) => c.f('clerkCalled'), 'The Phone Call', (c) => `found · ${c.g.flags.clerkCalled}`, (c) => [`The clerk at ${c.g.flags.clerkCalled} didn't call to get you in trouble. She told the officer that, three times. "I called because I have a daughter. I called because it's cold."`, 'The officer found you two streets over, and bought you a hot chocolate from the machine at the station, and let you hold it until your hands stopped shaking.', `${mom(c)} sent the clerk a card afterward. You don't know what it said. The clerk kept it on the front desk for years.${safeLine(c)}`]),
    F('fFakeCaught', 3, (c) => c.f('fakeCaught') && !c.g.fakeId, 'Laminated', 'found · the fake ID came back', (c) => [`The fake ID the clerk kept turned up at the station, clipped to a report. It had your face on it and a name that wasn't yours.`, `"Sixty bucks," the officer says, turning it over. "They got you. This is terrible. The hologram is a sticker from a cereal box."`, `${mom(c)} wants to be angry about it. She makes it about four seconds.${safeLine(c)}`]),
    F('fToldPlace', 4, (c) => c.f('toldParentPlace'), 'You Told Them Where', 'found · because you texted', (c) => [`You texted a friend's parent where you were. Maybe part of you wanted to be found. Maybe all of you did.`, `They drove through the night. When the headlights pulled into ${c.g.flags.toldParentPlace}, they were behind a sheriff's cruiser, and they got out before the car even stopped.`, `"Thank you for telling me," they kept saying. "Thank you for telling me." You don't regret it.${safeLine(c)}`]),
    F('fCharity', 3, (c) => c.f('charityExposed'), 'The Happy Paws Fund', 'found · the charity that wasn\'t', (c) => [`"${c.g.flags.charityExposed}," the officer reads off his notepad. "I called four animal shelters. I called the state charity registry. I called my mom, who knows every charity in the county."`, '"You made it up." You nod. "Kid, that\'s fraud. Small fraud. Very small fraud." He sighs. "I donated five dollars to it. I want it back."', `You give him five dollars. He gives it back, and buys you a burger with it.${safeLine(c)}`]),
    F('fCreepDiner', 3, (c) => c.f('creepDiner'), 'The Plate Number', 'found · the night at the diner', (c) => [`The plate number ${c.g.flags.creepDiner} wrote down that night belonged to a man the police had been looking for. Your description helped them find him.`, 'That\'s how they found you, too: the detective wanted to thank the kid who walked into the diner instead of into the car.', `"You did everything right," the detective says. "Every single thing. Most adults wouldn't have." You didn't feel brave. You felt scared. She says that's what brave is.${safeLine(c)}`]),
    F('fComfort', 2, (c) => Object.values(c.g.att || {}).some((x) => x >= 60), 'Nobody Left Behind', 'found · together to the end', (c) => [`When they find you, ${c.pl} ${c.n === 1 ? 'refuses' : 'refuse'} to be separated from you. Plants their feet. Holds your arm.`, '"We go together or we don\'t go." The officer, who has two kids of her own, looks at the two of you for a long moment and says, "Okay. Together."', `It was the best part of the whole thing, somehow: finding out you had people who'd do that.${safeLine(c)}`]),
    F('fHelped', 3, (c) => (c.g.helped || 0) >= 1, 'You Walked Someone Home', 'found · after helping someone else', (c) => [`The adult you walked that kid to called the police about you, the next day. Of course she did. She said it in the report: "the child who brought my niece to me is also a missing child."`, 'The officer who finds you already knows what you did. She says it before anything else: "You got another kid safe. You know that?"', `${mom(c)} hears the story from the officer before she hears it from you. She doesn't know whether to be terrified or proud. She decides on both.${safeLine(c)}`]),
    F('fKart', 2, (c) => c.g.lessons && c.g.lessons.kart >= 2, 'Pole Position', 'found · at the go-kart track', (c) => ['They find you at the go-kart track, mid-race, in the lead.', 'The officer waits at the fence until the checkered flag. You win. He claps. Then he waves you over, and your stomach drops, and he says "nice line through turn three" before he says anything else.', `${mom(c)} makes you promise never to drive anything until you're sixteen. You mostly keep the promise.${safeLine(c)}`]),
    F('fStallPawn', 2, (c) => Object.values(c.g.street || {}).some((x) => x >= 15) && c.tier === 'city', 'Everybody on the Block', 'found · the side streets', (c) => ['The woman from the alley stall, the pawn shop guy, the waitress, the fake-ID guy (who pretends he\'s never seen you): the whole side street watched the police walk you to the car.', 'The stall woman runs over with a hoodie. "It\'s cold. Take it. Don\'t argue." You don\'t argue.', `The side street never told anyone where you slept. They just made sure you were okay, in their way.${safeLine(c)}`]),
    F('fVillageStore', 2, (c) => c.tier === 'village', 'The Store Owner', (c) => `found · ${c.town}`, (c) => [`The woman at the ${c.town} general store knew for three days before she called. She told the deputy that, straight out: "I wanted to see if the kid would tell me. The kid didn't. So I called."`, 'She gives you a bag of peppermints and a bottle of juice for the ride. "You come back and visit," she says. "With your mother. I want to meet her."', `You do, the next summer. The two of them talk for an hour on the porch about you like you're not there.${safeLine(c)}`]),
    F('fBusiness2', 3, (c) => { const b = Object.values(c.g.biz || {}).filter(Boolean)[0]; return b && b.shifts >= 6 && c.n >= 1; }, 'Last Shift', 'found · the whole team', (c) => [`You were halfway through a shift when they came. ${c.pl} kept working until the last customer was served. Professionalism.`, 'The officer counted the cash box with you, twice, and wrote it on the report: "business proceeds, $ amount, to be returned to minors." It\'s the only police report in the county with a profit margin on it.', `Every one of you went home with an equal share.${safeLine(c)}`]),
    F('fBaseBarn', 3, (c) => c.g.base && c.g.base.type === 'barn', 'The Farmer\'s Barn', 'found · the hayloft', (c) => ['The farmer who owned the barn found you, eventually. He stood at the bottom of the ladder for a long time before he said anything.', '"You fixed the loft door," he said. "That\'s been broken since 1996." He called the sheriff. Then he made you eggs while you waited.', `He asks the deputy to tell your family you're welcome back anytime. "Summers," he says. "Work, not hiding."${safeLine(c)}`]),
    F('fBaseBuilding', 3, (c) => c.g.base && c.g.base.type === 'building' && c.tier !== 'village', 'Condemned', 'found · the old building', (c) => ['A city inspector came to condemn the building and found your curtains, your bed, your heater, your very neat stack of library books.', 'He sat down on your crate and read the top book for a while before he called anyone. "My daughter loves this one," he said.', `The building got torn down in spring. You drove past it once, with ${mom(c)}, and she held your hand.${safeLine(c)}`]),
    F('fBaseCamp', 3, (c) => c.g.base && c.g.base.type === 'camp', 'The Ranger', 'found · the forest camp', (c) => ['The ranger followed the smell of your campfire. She stood at the edge of your clearing and said "I\'m not going to yell. Is anybody hurt?"', 'She checked the fire ring, the tarp, the food hung from a branch, and whistled. "Somebody taught you right." Nobody taught you. You watched videos.', `She drives you out in the ranger truck, and lets you work the radio.${safeLine(c)}`]),
    F('fRoomLate', 2, (c) => c.g.room && c.g.room.late, 'Past Due', 'found · owing the motel', (c) => ['You were two nights behind on the room when they came. The officer asked the clerk what you owed.', 'Then the officer paid it. Out of her own wallet. "Kid shouldn\'t leave anywhere owing money," she said. "Bad habit to start."', `${mom(c)} paid her back the next day, with a pie.${safeLine(c)}`]),
    F('fDisguiseKid', 2, (c) => c.g.look && c.g.look.hair && !c.g.look.dye, 'The Haircut', 'found · the bad haircut', (c) => ['You cut your own hair in a gas station bathroom. It shows. The officer tries very hard not to comment.', `${mom(c)} does not try at all. "Oh, baby. Oh, your HAIR." She takes you to her salon the next day. The stylist says "who did this?" and you say "me," and she says "I can tell."`, `It grows back. It always does.${safeLine(c)}`]),
    F('fWinterMotel', 4, (c) => SH.World2 && SH.World2.season(c.g.t) === 'winter' && c.g.room, 'Snowed In', 'found · the motel in the snow', (c) => ['The snowstorm closed the highway and filled the motel with stranded truckers and one family and one very small, very recognizable guest.', 'The state trooper stranded there too recognized you over the breakfast waffles. She waited until you\'d finished eating.', `You were all stuck there two more days. She taught you to play gin rummy. By the time the roads opened, you'd told her everything.${safeLine(c)}`]),
    F('fGoneNearly', 3, (c) => c.f('goneOffered') && c.days >= 45, 'So Close', 'found · almost gone for good', (c) => ['You were so close to disappearing. You\'d built a whole life. You could feel it closing around you like a warm coat.', 'And then someone saw a picture of you, and recognized a scar on your chin, and it all came apart in one afternoon.', `The strangest part: part of you was relieved. ${mom(c)} hugged you and you hugged her back and you realized you'd been waiting for this for forty-five days.${safeLine(c)}`]),
  ]);
})(window.SH);
