/* SMALL HOURS — how you find work, how the world reacts to your money, and the Hustle app. All events are engine data. */
(function (SH) {
  const J = SH.Jobs, P = SH.Phone, U = SH.util;
  const pushJ = (t) => () => SH.Phone.push('jordan', 'jordan', t);
  SH.Engine.register([
    /* ---- discovering gigs & business ideas ---- */
    { id: 'h_rake_note', pool: 'mundane', weight: 12, once: true, when: ['athome', 'hour > 14', 'hour < 19', 'day >= 1'], title: 'A Note on the Door', text: 'Taped to your front door, in shaky capitals: "KID — LEAVES. $12. SEE ME. — HENDERSON (NEXT DOOR, THE GOOD LAWN)."', choices: [{ t: 'Pocket it', effects: ['flag gigRake'], text: 'Rake leaves at home (weekends, or after school when it\'s dry). October is on your side: they never stop falling.', textCls: 'good' }] },
    { id: 'h_candy_idea', pool: 'notify', weight: 10, once: true, when: ['phoneok', 'day >= 2', 'hour > 15', 'hour < 22'], effects: [pushJ('bro devon made like $40 last week selling candy at lunch. costco box. we should do that. well YOU should, my mom checks my backpack'), 'flag bizCandy'] },
    { id: 'h_art_ask', pool: 'mundane', weight: 10, once: true, when: ['loc == school', 'weekday', 'hour > 10', 'hour < 15', 'day >= 2'], title: 'Maya\'s Request', who: 'maya', text: 'Maya Chen slides into the seat next to you with her sketchbook open to a lopsided dragon. "Okay, so. I saw your drawing in science. Can you draw my Skyforge character? I\'ll pay you. Three dollars. Four if it has wings."',
      choices: [{ t: '"Deal. Five with wings."', effects: ['flag bizArt', 'money 4', 'stat.mood +6'], text: 'She pays up front. $4 and a promise to tell everyone. You can draw commissions in your room and sell them at lunch.', textCls: 'good' }, { t: '"I\'m not that good."', effects: ['flag bizArt'], text: '"Literally you are. Think about it." She leaves a dollar on your desk anyway, like a tip. You can draw commissions in your room and sell them at lunch.' }] },
    { id: 'h_stand_lily', pool: 'mundane', weight: 10, once: true, when: ['athome', 'lily == home', 'day >= 3'], title: 'Lily Has a Plan', who: 'lily', text: 'Lily bursts in holding a poster that says LEMONAID (sp?) with a turtle drawn on it. "We should do a stand! In the park! You do the money and I do the YELLING."',
      choices: [{ t: '"Okay. Business partners."', effects: ['flag bizStand', 'rel.lily +8'], text: 'She shakes your hand very seriously. Buy supplies at QuikMart; run the stand at the park on weekends. Cold days: cocoa. Warm days: lemonade.', textCls: 'good' }, { t: '"Maybe later, Lil."', effects: ['flag bizStand'], text: 'She tapes the poster to your door. It stays there. (Supplies at QuikMart, stand at the park on weekends.)' }] },
    { id: 'h_carry_chat', pool: 'notify', weight: 8, once: true, when: ['phoneok', 'day >= 3', 'hour > 16', 'hour < 22'], effects: [() => SH.Phone.push('class', 'class', 'devonnn: anyone good at skyforge?? paying $5 to whoever gets me past the ice wyrm. im not bad im just unlucky'), 'flag bizCarry'] },
    { id: 'h_carwash', pool: 'notify', weight: 9, once: true, when: ['phoneok', 'wd == 4', 'hour > 15'], effects: [pushJ('CAR WASH SAT. school lot. 10am. my uncle has a hose and a dream. we split everything 50/50. u in?? 🧽'), 'flag gigCarwash'] },
    { id: 'h_dolores_work', pool: 'mundane', weight: 10, once: true, when: ['loc == diner', 'phase == home'], title: 'Dolores', who: 'dolores', text: 'Dolores catches you reading the pie board. "You look like somebody who could use five bucks. I need flyers passed out on weekends. Fifteen dollars and a slice. You in, hon?"', choices: [{ t: '"I\'m in."', effects: ['flag gigFlyers', 'rel.dolores +5'], text: 'Weekends, 10 to 4, dry days. Ask at the diner.', textCls: 'good' }] },
    /* ---- the world reacts to your money ---- */
    { id: 'h_rival', pool: 'mundane', weight: 6, once: true, when: [() => J.state().candy.sold >= 15, 'loc == school', 'weekday'], text: 'Devon has set up a rival operation by the water fountain: Takis, fifty cents, with a laminated menu. "It\'s called capitalism," he says. Your sales are going to feel it for a few days.', effects: [() => { J.state().rival = SH.day() + 4; }] },
    { id: 'h_mom_money', pool: 'mundane', weight: 14, once: true, when: [() => J.state().earned >= 25, 'athome', 'mom == home'], title: 'Laundry Day', who: 'mom', text: 'Mom comes in holding your jeans. And a wad of bills she found in the pocket. "Baby. Where did you get this much money?"',
      choices: [{ t: 'Tell her the truth', sub: 'The jobs, the hustles, all of it.', cls: 'safe', effects: ['rel.mom +8', 'stat.mood +6', 'flag momKnowsHustle'], text: 'She sits on your bed and listens to the whole thing, the leaves and the candy and the drawings. Then she laughs — a real laugh, the first one in weeks. "You get that from your grandpa." Then, quieter: "Don\'t let Rick see it. Okay? Just... keep it somewhere safe."', textCls: 'good' },
        { t: '"Jordan\'s mom paid me for… stuff."', effects: ['susp +10', 'rel.mom -4'], text: 'She looks at you for a long time. "I\'m going to call Jordan\'s mom." She doesn\'t. But now she\'s watching.' }] },
    { id: 'h_rick_borrow', pool: 'mundane', weight: 12, cooldown: 96, when: ['money >= 25', 'athome', 'rick == home', 'drunk >= 1', 'hour > 17'], title: 'A Loan', who: 'rick', text: 'Rick is standing in your doorway. "Heard you\'ve been working. Good for you. Real proud." He holds out his hand. "Lend me twenty till Friday."',
      choices: [{ t: 'Give him $20', effects: ['money -20', 'rel.rick +4', 'flag rickBorrowed'], text: 'He takes it without counting it. Friday comes and goes. He never mentions it again, and neither do you.' },
        { t: '"I\'m saving it."', when: ['drunk < 2'], effects: ['rel.rick -8', 'stat.stress +8'], text: '"Saving it. For WHAT." He stares at you a second too long. Then he goes back downstairs. You move the money to the shoebox.' },
        { t: '"I\'m saving it."', when: ['drunk >= 2'], cls: 'hot', effects: ['rel.rick -12', 'stat.stress +14', 'money -20', 'flag rickTookMoney'], text: 'He doesn\'t argue. He just takes your wallet off the desk, pulls out a twenty, and drops the wallet on the floor. "Rent," he says. You stand there shaking long after he\'s gone.' }] },
    { id: 'h_tyler_tax', pool: 'mundane', weight: 10, cooldown: 120, when: ['loc == school', 'weekday', 'money >= 10', 'rel.tyler < -15', () => J.state().earned > 10], title: 'The Tax', who: 'tyler', text: 'Tyler falls into step beside you. "Heard you\'re rich now, candy boy. There\'s a tax. Five bucks."',
      choices: [{ t: 'Pay him', effects: ['money -5', 'stat.stress +5', 'stat.mood -5'], text: 'He pockets it and smirks. It\'s not the five dollars. It\'s the smirk.' }, { t: '"No."', effects: ['rel.tyler -5', 'stat.stress +8', 'rel.tyler +8'], text: 'He shoves your shoulder — not hard, just enough. "Whatever. You\'re boring." And he leaves. Weirdly, he seems to respect it.' }, { t: '"Want to go in on it? You\'re scary. I\'m organized."', when: ['flag.tylerTruce'], effects: ['rel.tyler +15'], text: 'He blinks. Nobody has ever offered Tyler a job. "...Maybe." (He never does. But he stops calling you candy boy.)' }] },
    { id: 'h_proud', pool: 'notify', weight: 6, once: true, when: [() => J.state().earned >= 40, 'phoneok'], effects: [() => SH.Phone.push('grandma', 'grandma', 'Your mother told me you\'ve been working, raking and selling your drawings! My entrepreneur. Your grandpa sold nightcrawlers out of a coffee can when he was your age. Save some. Spend some on something silly.')] },
  ]);

  /* ---- Hustle app ---- */
  (P.extraApps = P.extraApps || []).push({ at: 3, app: ['hustle', '💼', 'Hustle', '#0f9d58'] });
  P.V.hustle = function (body) {
    const G = SH.G, B = J.state(), esc = P.esc, wk = Math.floor((SH.day() - 1) / 7);
    const biz = [];
    if (SH.f('bizCandy')) biz.push(['🍫', 'Candy at lunch', `${B.candy.stock} bars in stock · ${B.candy.sold} sold`, J.repWord(B.candy.rep) + (B.candy.ban > SH.day() ? ' · Mr. Dale is watching you' : B.rival > SH.day() ? ' · Devon is undercutting you' : ''), 'Buy at QuikMart ($8/24). Sell at school, lunch or right after.']);
    if (SH.f('bizArt')) biz.push(['🎨', 'Drawings', `${B.art.stock} ready · ${B.art.sold} sold`, J.repWord(B.art.rep), 'Draw in your room (1 hr). Sell at school.']);
    if (SH.f('bizStand')) biz.push(['🥤', 'Drink stand', `${B.stand.cups} cups left`, SH.tempF() < 58 ? 'Cold out: cocoa weather' : 'Lemonade weather-ish', 'Supplies at QuikMart ($6/20). Park, weekends 10–5.']);
    if (SH.f('bizCarry')) biz.push(['⚔️', 'Skyforge carries', `${B.carry.runs} done`, J.repWord(B.carry.rep), 'Your room, evenings. Eats battery. And homework time.']);
    const gigs = J.GIGS.filter((g) => !g.flag || SH.f(g.flag)).filter((g) => g.id !== 'redeem').map((g) => `<div class="memrow"><span>🧾</span><div>${esc(g.label)}<small>${esc([].concat(g.loc).map((l) => SH.LOC[l].name).join(' / '))} · ${esc(typeof g.sub === 'function' ? g.sub() : g.sub)}</small></div></div>`).join('');
    body.innerHTML = P.hdr('💼 Hustle') + `<div class="appbody"><div class="post" style="text-align:center"><div style="color:#888;font-size:11px">EARNED THIS WEEK</div><div style="font-size:30px;font-weight:200">$${(B.week[wk] || 0).toFixed(2)}</div><div style="color:#888;font-size:11px">All-time $${B.earned.toFixed(2)} · on you $${G.money.toFixed(2)}${G.phase === 'home' ? ' · shoebox $' + G.shoebox : ''}${B.cans ? ' · ' + B.cans + ' cans' : ''}</div></div>
      <div class="sech">YOUR BUSINESSES</div>${biz.map(([i, n, s, r, how]) => `<div class="post"><div class="who">${i} ${esc(n)}</div>${esc(s)}<div class="meta">Word: ${esc(r)}</div><div class="meta">${esc(how)}</div></div>`).join('') || '<p class="muted">No business yet. Keep your ears open: somebody always needs something.</p>'}
      <div class="sech">GIGS YOU KNOW ABOUT</div>${gigs}
      <div class="sech">LEDGER</div>${B.ledger.slice(-10).reverse().map((x) => `<div class="setrow"><span>${esc(x.d)}<small>${SH.dateStr(x.t)}</small></span><span style="color:${x.a < 0 ? '#ff6b6b' : '#7bd88f'}">${x.a < 0 ? '-' : '+'}$${Math.abs(x.a).toFixed(2)}</span></div>`).join('') || '<p class="muted">Nothing yet.</p>'}</div>`;
  };

  /* ---- station props & overheard lines ---- */
  if (SH.PROPS) SH.PROPS.station = [
    { id: 'st_board', ic: '🕰️', l: 'Look at the station clock', min: 3, texts: ['The big clock over the doors says 3:15. It has said 3:15 since 1987. There\'s a newer clock under it that nobody looks at.'] },
    { id: 'st_map', ic: '🗺️', l: 'Read the route map', min: 4, texts: ['A faded map of the Northline: Harlow, Millbrook, Cedar Falls, then little dots all the way to the capital. Somebody drew a heart at Cedar Falls in pen.'] },
    { id: 'st_vend', ic: '🥨', l: 'Vending machine', sub: '$1.75', cost: 1.75, min: 3, texts: ['Pretzels from 2019, probably. Still crunchy. Trains can\'t stop time but vending machines can.'], fx: ['stat.full +10'] },
  ];
  if (SH.OVERHEAR) SH.OVERHEAR.station = ['"Train 41 to Cedar Falls, now boarding on Platform 2." A man sprints past with a coffee held perfectly level.', 'A conductor on his break: "—twelve-year-old tried it last spring. Found him in the bathroom, crying. Nicest kid. His grandma came down to get him."', '"I don\'t care if it\'s cheaper, Linda, I\'m not taking the 6:45."'];
})(window.SH);
